### ISSUE TITLE
Updated app and still can't update price.

### ISSUE THREAD

**Issue by CodeDecent** [slockit/usn-mvp#8]
Android 8 Stable
Pi & Cloud/Slock.it

A followup to this closed issue
https://github.com/slockit/usn-mvp/issues/6

I updated the app yesterday. Imported my last wallet. Went to my slocks...Cant reactivate them. Cloud accounts still there. Edited the price for each slock/switch from 192 mketh to $3 usd and didn't update. Do I have to delete all accounts and do it all again?

**Comment by nomoreboredom** [comment]
Hi @CodeDecent,

The fix is implemented now. As it turns out, some mistake on the creation of the meta data broke the process. 

Normally after removing/importing the accounts you would not need to repeat the process, but in this case you may require. A new package will be delivered before the end of this week so I am keeping this issue open for now, will notify you here as well when the apk is updated so we can confirm together.

Thanks for reporting the issue!

**Comment by CodeDecent** [comment]
@nomoreboredom thank you. I received an Android update. I will keep you updated.

**Comment by CodeDecent** [comment]
@nomoreboredom Changed the price to each and still crashes after doing features. Then goes blank. Back button crashes the app.

**Comment by nomoreboredom** [comment]
Hi @CodeDecent 
Thanks a lot for your speedy input! 

I have just tried to create a slock (coffeetype) and then edit the price, worked without a problem.
Was this slock from the previous package? Can you perhaps try to repeat the process, including creating the slock again? 

Also, from the snapshot you have attached, it seems like you are not runnning the most recent version? Can you confirm you have 0.0.19 installed? 

Thanks!

**Comment by simon-jentzsch** [comment]
fixed
